export class ContactActions {
  static CLEAR = 'CLEAR_CONTACT';
  static LOAD_FROM_DB = 'LOAD_CONTACT_FROM_DB';
  static UPDATE_PHONE_NUM = 'UPDATE_CONTACT_PHONE_NUM';
  static UPDATE_LOCATION_WITH_ACCOUNT = 'UPDATE_CONTACT_LOCATION_WITH_ACCOUNT';
  static UPDATE_LOCATION = 'UPDATE_CONTACT_LOCATION';
  static UPDATE_WITHOUT_LOCATION = 'UPDATE_CONTACT_WITHOUT_LOCATION';
  static UPDATE_ACCOUNT = 'UPDATE_CONTACT_ACCOUNT';
  static UPDATE: any;
}
